project_id = "znbhusklmbfyynjytdne"

[auth]
site_url = "https://nestguide.lovable.app"

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.email.template.magic_link]
subject = "Your NestGuide Login Code"
content_path = "./supabase/templates/magic_link.html"